version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: chat-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: chat_db
    ports:

      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: